"""
Report Generator.

Combines summary.csv, trade_analysis.csv, performance_metrics.csv,
monthly_pnl.csv and portfolio_summary.csv from a run into a single
clean HTML report.

Usage:
    python -m analytics.report_generator reports/RUN_XXXXXXXX_XXXXXX/
"""

import sys
import pandas as pd
from pathlib import Path
from datetime import datetime


HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backtest Report - {run_id}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: #0f1117; color: #e0e0e0; padding: 32px; }}
  h1 {{ font-size: 24px; color: #ffffff; margin-bottom: 4px; }}
  h2 {{ font-size: 16px; color: #90caf9; margin: 32px 0 12px; text-transform: uppercase;
        letter-spacing: 1px; border-bottom: 1px solid #1e2a3a; padding-bottom: 6px; }}
  .meta {{ color: #888; font-size: 13px; margin-bottom: 32px; }}
  .cards {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 8px; }}
  .card {{ background: #1a1f2e; border: 1px solid #1e2a3a; border-radius: 10px;
           padding: 20px 24px; min-width: 160px; flex: 1; }}
  .card .label {{ font-size: 11px; color: #888; text-transform: uppercase;
                  letter-spacing: 0.5px; margin-bottom: 6px; }}
  .card .value {{ font-size: 26px; font-weight: 600; color: #ffffff; }}
  .card .value.green {{ color: #4caf50; }}
  .card .value.red   {{ color: #ef5350; }}
  .card .value.blue  {{ color: #90caf9; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 8px; }}
  th {{ background: #1a1f2e; color: #90caf9; padding: 10px 12px; text-align: left;
        font-weight: 500; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }}
  td {{ padding: 9px 12px; border-bottom: 1px solid #1a1f2e; }}
  tr:hover td {{ background: #1a1f2e; }}
  .green {{ color: #4caf50; }}
  .red   {{ color: #ef5350; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 10px;
            font-size: 11px; font-weight: 500; }}
  .badge.green {{ background: #1b3a2a; color: #4caf50; }}
  .badge.red   {{ background: #3a1b1b; color: #ef5350; }}
  .section {{ background: #13171f; border: 1px solid #1e2a3a; border-radius: 10px;
              padding: 24px; margin-bottom: 24px; overflow-x: auto; }}
  .monthly-bar {{ display: inline-block; height: 12px; border-radius: 2px;
                  vertical-align: middle; margin-right: 6px; }}
  footer {{ margin-top: 40px; font-size: 12px; color: #444; text-align: center; }}
</style>
</head>
<body>

<h1>Backtest Report</h1>
<div class="meta">Run ID: {run_id} &nbsp;|&nbsp; Generated: {generated_at} &nbsp;|&nbsp;
Strategy: ChecklistStrategy &nbsp;|&nbsp; Period: {start_date} → {end_date}</div>

<h2>Portfolio Summary</h2>
<div class="cards">
  <div class="card"><div class="label">Total Trades</div>
    <div class="value blue">{total_trades}</div></div>
  <div class="card"><div class="label">Win Rate</div>
    <div class="value {wr_color}">{overall_win_rate}%</div></div>
  <div class="card"><div class="label">Total PnL</div>
    <div class="value {pnl_color}">₹{total_pnl}</div></div>
  <div class="card"><div class="label">Avg PnL / Trade</div>
    <div class="value {avg_color}">₹{avg_pnl}</div></div>
  <div class="card"><div class="label">Portfolio Sharpe</div>
    <div class="value blue">{sharpe}</div></div>
  <div class="card"><div class="label">Profitable Stocks</div>
    <div class="value blue">{profitable_stocks} / {total_stocks}</div></div>
</div>

<h2>Stock Rankings</h2>
<div class="section">
{ranking_table}
</div>

<h2>Risk-Adjusted Performance</h2>
<div class="section">
{metrics_table}
</div>

<h2>Trade Quality Analysis</h2>
<div class="section">
{trade_analysis_table}
</div>

<h2>Monthly PnL Breakdown</h2>
<div class="section">
{monthly_table}
</div>

<footer>Generated by algo-trading-bot analytics pipeline</footer>
</body>
</html>
"""


def _pnl_color(val):
    try:
        return "green" if float(str(val).replace(",","")) >= 0 else "red"
    except:
        return ""


def _df_to_html(df: pd.DataFrame, color_col: str = None,
                pct_cols: list = None, pnl_cols: list = None) -> str:
    rows = []
    headers = "".join(f"<th>{c}</th>" for c in df.columns)
    rows.append(f"<tr>{headers}</tr>")

    for _, row in df.iterrows():
        cells = []
        for col in df.columns:
            val = row[col]
            cell_class = ""

            if pct_cols and col in pct_cols:
                try:
                    cell_class = "green" if float(val) >= 0 else "red"
                except:
                    pass

            if pnl_cols and col in pnl_cols:
                try:
                    cell_class = "green" if float(val) >= 0 else "red"
                except:
                    pass

            if col == color_col:
                try:
                    cell_class = "green" if float(val) >= 0 else "red"
                except:
                    pass

            if isinstance(val, float):
                val = f"{val:,.2f}"

            if cell_class:
                cells.append(f'<td class="{cell_class}">{val}</td>')
            else:
                cells.append(f"<td>{val}</td>")

        rows.append(f"<tr>{''.join(cells)}</tr>")

    return f"<table><thead>{rows[0]}</thead><tbody>{''.join(rows[1:])}</tbody></table>"


def generate(run_dir: str):
    run_path = Path(run_dir)
    run_id   = run_path.name

    # load all CSVs
    summary    = pd.read_csv(run_path / "summary.csv")
    portfolio  = pd.read_csv(run_path / "portfolio_summary.csv").iloc[0]
    metrics    = pd.read_csv(run_path / "performance_metrics.csv")
    trade_anal = pd.read_csv(run_path / "trade_analysis.csv")
    monthly    = pd.read_csv(run_path / "monthly_pnl.csv")

    # date range from trade history
    trades     = pd.read_csv(run_path / "trade_history.csv")
    start_date = trades["entry_date"].min()[:7]
    end_date   = trades["exit_date"].max()[:7]

    # portfolio card values
    total_pnl  = f"{portfolio['total_pnl']:,.2f}"
    avg_pnl    = f"{portfolio['avg_pnl_per_trade']:,.2f}"
    wr         = portfolio["overall_win_rate"]

    # ranking table — top 15 cols
    rank_cols  = ["rank", "symbol", "ending_capital", "total_return_pct",
                  "total_trades", "win_rate_pct", "max_drawdown_pct", "sharpe_ratio"]
    rank_df    = summary[rank_cols].head(15).copy()

    # metrics table
    met_cols   = ["stock", "total_return_pct", "max_drawdown_pct",
                  "sharpe", "calmar", "max_dd_duration_days", "rolling_win_rate_pct"]
    met_df     = metrics[met_cols].head(20).copy()

    # trade analysis table
    ta_cols    = ["stock", "total_trades", "win_rate_pct", "avg_win",
                  "avg_loss", "rrr", "expectancy", "profit_factor",
                  "max_consec_losses", "stop_loss_rate_pct"]
    ta_df      = trade_anal[ta_cols].head(20).copy()

    # monthly table with visual bar
    monthly["bar"] = monthly["total_pnl"].apply(
        lambda x: f'<span class="monthly-bar" style="width:{min(abs(x)/2000*80,120):.0f}px;'
                  f'background:{"#4caf50" if x >= 0 else "#ef5350"}"></span>'
    )
    monthly["total_pnl"] = monthly["total_pnl"].apply(
        lambda x: f"+{x:,.0f}" if x >= 0 else f"{x:,.0f}"
    )
    mon_cols = ["month", "bar", "total_pnl", "trade_count", "win_rate_pct"]
    mon_df   = monthly[mon_cols].copy()

    html = HTML_TEMPLATE.format(
        run_id         = run_id,
        generated_at   = datetime.now().strftime("%Y-%m-%d %H:%M"),
        start_date     = start_date,
        end_date       = end_date,
        total_trades   = int(portfolio["total_trades"]),
        overall_win_rate = wr,
        wr_color       = "green" if wr >= 45 else "red",
        total_pnl      = total_pnl,
        pnl_color      = _pnl_color(portfolio["total_pnl"]),
        avg_pnl        = avg_pnl,
        avg_color      = _pnl_color(portfolio["avg_pnl_per_trade"]),
        sharpe         = portfolio["portfolio_sharpe"],
        profitable_stocks = int(portfolio["profitable_stocks"]),
        total_stocks   = int(portfolio["total_stocks"]),
        ranking_table  = _df_to_html(rank_df, color_col="total_return_pct"),
        metrics_table  = _df_to_html(met_df,  color_col="calmar"),
        trade_analysis_table = _df_to_html(ta_df, color_col="expectancy"),
        monthly_table  = mon_df.to_html(index=False, escape=False,
                            classes="", border=0).replace(
                            '<table class="" border="0">', "<table>"),
    )

    out_path = run_path / "report.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"Report saved → {out_path}")
    return out_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python -m analytics.report_generator <run_dir>")
        sys.exit(1)

    path = generate(sys.argv[1])
    print(f"Open in browser: open {path}")
